//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NetPerSec.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_NETWORKLIGHTS_DIALOG        102
#define IDD_CONFIG_DLG                  102
#define IDD_STATS_DLG                   102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_SESSION_DLG                 106
#define IDD_TOTALS_DLG                  107
#define IDD_OPTIONS_DLG                 108
#define IDD_GRAPH_DLG                   109
#define IDD_COLOR_DLG                   109
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDI_MAINFRAME                   140
#define IDI_BARGRAPH                    144
#define IDD_COLORCUBE_DLG               145
#define IDB_LOGO                        147
#define IDI_HISTOGRAM                   158
#define IDC_RECV_CURRENT                1000
#define IDS_RECV_CURRENT                1000
#define IDC_RECV_AVERAGE                1001
#define IDS_RECV_AVERAGE                1001
#define IDC_RECV_MAXIMUM                1002
#define IDS_RECV_GRAPH                  1002
#define IDC_RECV_TOTAL                  1003
#define IDS_SCALE_SLIDER_RECV           1003
#define IDC_SENT_CURRENT                1004
#define IDC_VERSION                     1004
#define IDS_INETMIB_ERR                 1004
#define IDC_SENT_AVERAGE                1005
#define IDC_COPYRIGHT                   1005
#define IDS_CREATEWINDOW_ERR            1005
#define IDC_SENT_MAXIMUM                1006
#define IDS_STARTUP_ERR                 1006
#define IDC_SENT_TOTAL                  1007
#define IDC_RADIO1                      1007
#define IDC_ICON_BARGRAPH               1007
#define IDC_USE_SNMP                    1007
#define IDS_DUN_ERR                     1007
#define IDC_BPS                         1008
#define IDS_SNMPINIT_ERR                1008
#define IDC_RADIO3                      1009
#define IDC_BYTES                       1009
#define IDS_SNMPQUERY_ERR               1009
#define IDC_CHECK1                      1010
#define IDC_STARTWITHWINDOWS            1010
#define IDC_AUTOSCALE_SENT              1010
#define IDS_SNMPFAIL_ERR                1010
#define IDC_ONTOP                       1011
#define IDC_AUTOSCALE_RECV              1011
#define IDS_SNMPAPI_ERR                 1011
#define IDC_SAMPLE_SLIDER               1012
#define IDC_BARGRAPH                    1012
#define IDS_INETMIB1_ERR                1012
#define IDC_AVERAGE_SLIDER              1013
#define IDC_AVERAGE_VALUE               1014
#define IDC_SAMPLE_VALUE                1015
#define IDC_PROGRESS1                   1016
#define IDC_EDIT1                       1017
#define IDC_AUTO_CONFIGURE              1018
#define IDC_MODEM                       1019
#define IDC_USER_DEFINED                1020
#define IDC_MODEM_COMBO                 1021
#define IDC_USER_DEFINED_EDIT           1022
#define IDC_RESET_TODATE                1023
#define IDC_RESET_TODAY                 1024
#define IDC_SHOW_BITS                   1024
#define IDC_SHOW_BYTES                  1025
#define IDC_HISTOGRAM                   1026
#define IDC_SCALE                       1027
#define IDC_SCALE_TEXT                  1028
#define IDC_CURRENT_RECV_OPTION         1029
#define IDC_AVE_RECV_OPTION             1030
#define IDC_MAX_RECV_OPTION             1031
#define IDC_SCALE_MAX_RECV              1032
#define IDC_SCALE_MID_RECV              1033
#define IDC_CURRENT_SENT_OPTION         1034
#define IDC_AVE_SENT_OPTION             1035
#define IDC_MAX_SENT_OPTION             1036
#define IDC_SCALE_MAX_SENT              1037
#define IDC_SCALE_MID_SENT              1038
#define IDC_SCALE_SLIDER                1039
#define IDC_SCALE_SLIDER_RECV           1039
#define IDC_SENT_GRAPH                  1040
#define IDC_RECV_GRAPH                  1041
#define IDC_SENT_ZERO                   1042
#define IDC_RECV_ZERO                   1043
#define IDC_SCALE_SLIDER_SENT           1044
#define IDC_RESET_DATA                  1045
#define IDC_LINEGRAPH                   1046
#define IDC_SCALE_TEXT_RECV             1047
#define IDC_SCALE_TEXT_SENT             1048
#define IDC_GROUP_RECV                  1049
#define IDC_GROUP_SENT                  1050
#define IDC_STATS_LIST                  1053
#define IDC_UPDATE                      1054
#define IDC_AVERAGE_MIN                 1055
#define IDC_AVERAGE_MAX                 1056
#define IDC_COLOR_AVE                   1059
#define IDC_COLOR_BACK                  1060
#define IDC_COLOR_RECV                  1063
#define IDC_COLOR_SENT                  1064
#define IDC_DEFAULT_COLORS              1065
#define IDC_UNDO                        1066
#define IDC_SAMPLE_ICON                 1067
#define IDC_COLOR_ICON_BACK             1068
#define IDC_ICON_HISTOGRAM              1069
#define IDC_COLOR_ICON_BACK_TEXT        1070
#define IDC_SENT_GRAPH_WINDOW           1071
#define IDC_RECV_GRAPH_WINDOW           1072
#define IDC_COLOR1                      1081
#define IDC_COLOR2                      1082
#define IDC_COLOR3                      1083
#define IDC_COLOR4                      1084
#define IDC_COLOR5                      1085
#define IDC_COLOR6                      1086
#define IDC_COLOR7                      1087
#define IDC_COLOR8                      1088
#define IDC_COLOR9                      1089
#define IDC_COLOR10                     1090
#define IDC_COLOR11                     1091
#define IDC_COLOR12                     1092
#define IDC_COLOR13                     1093
#define IDC_COLOR14                     1094
#define IDC_COLOR15                     1095
#define IDC_COLOR16                     1096
#define IDC_SAMPLE_GROUP                1097
#define IDC_AVERAGE_GROUP               1098
#define IDC_USE_DUN                     1099
#define IDC_INTERFACES                  1100
#define IDC_MONITOR_ADAPTER             1101
#define ID_PROPERTIES                   32774
#define IDM_ABOUT                       32775

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        188
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
